config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 root 'home#index'
   match '/about_us',   to: 'home#about_us',   via: :get
   match '/contact_us', to: 'home#contact_us', via: :get
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ActiveRecord::base

	belongs_to :search_school

end

app/models/rtegrade.rb
class RTEGrade < ActiveRecord::Base

end

app/models/school_category.rb
class SchoolCategory < ActiveRecord::Base

	has_many :search_school
	
end

app/models/school_management.rb
class SchoolManagement < ActiveRecord::Base

	has_many :search_school

end

app/models/school_type.rb
class SchoolType < ActiveRecord::Base

	has_many :search_school

end

app/models/search_school.rb
class SearchSchool < ActiveRecord::Base

	has_many :reviews
	belongs_to :school_category
	belongs_to :school_management
	belongs_to :school_type
	belongs_to :RTEgrade

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about_us
  end

  def contact_us
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def about_us
  end

  def contact_us
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  def index
  end
end

app/controllers/rtegrades_controller.rb
class RTEGradesController < ApplicationController
  
end

app/controllers/school_categories_controller.rb
class SchoolCategoriesController < ApplicationController
  
end

app/controllers/school_managements_controller.rb
class SchoolManagementsController < ApplicationController
  
end

app/controllers/school_types_controller.rb
class SchoolTypesController < ApplicationController
  
end

app/controllers/search_schools_controller.rb
class SearchSchoolsController < ApplicationController

	def index

	end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/about_us.html.erb
<%= render 'layouts/header' %>
        <div class="container page-content">
            <div class="row">
                <div class="span12">
                    <div class="box-container">
                        <div class="padding30">
                            <h2 class="page-title">Wide page</h2>
                            <p>Pellentesque habitant morbi tristique senectus et netus et malesuada
                                fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae,
                                ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam
                                egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend
                                leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum
                                erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean
                                fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci,
                                sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar
                                facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor
                                neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat
                                volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis
                                luctus, metus</p>
                            <p>Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit
                                amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros
                                ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in
                                turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus
                                faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat.
                                Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor,
                                facilisis luctus, metus</p>
                            <p>Donec eu libero sit amet quam egestas semper. Aenean ultricies mi
                                vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien
                                ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo
                                vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt
                                condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui.
                                Donec non enim in turpis pulvinar facilisis. Pellentesque habitant morbi
                                tristique senectus et netus et malesuada fames ac turpis egestas.
                                Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet,
                                ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi
                                vitae est. Mauris placerat eleifend leo.</p>
                            <p>Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat
                                wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean
                                fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci,
                                sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar
                                facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor
                                neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat
                                volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis
                                luctus, metus</p>
                            <p>Pellentesque habitant morbi tristique senectus et netus et malesuada
                                fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae,
                                ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam
                                egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend
                                leo.</p>
                        </div>
                    </div>
                </div>
                <!-- .span12 -->
            </div>
            <!-- .row -->
        </div>
        <!-- .container -->
        <div class="container">
            <div class="row">
                <div class="home-bottom-top">
                    <div class="span4">
                        <div class="info-box">
                            <h2 class="secion-title">Why choose us?</h2>
                            <p>Lorem ipsum dolor sit amet consectetur incididunt ut labore et dolore
                                magna aliqua adipisicing elit seddo eiusmod tempor.</p>
                            <p>Sed perspiciatis unde omnisiste natus error voluptatem remopa
                                accusantium doloremque laudantium, totam rem aperiam.</p>
                            <a class="serif italic" href="#" title="Continue">Continue &raquo;</a>
                        </div>
                    </div>
                    <!-- .span4 -->
                    <div class="span4">
                        <div class="info-box">
                            <h3 class="info-head">Designed for your business</h3>
                            <div class="row clearfix">
                                <div class="pull-left icons hidden-phone">
                                    <i class="icon-briefcase"></i>
                                </div>
                                <div class="span3">
                                    <p>Lorem ipsum dolor sit amet consectetur incididunt ut labore et dolore
                                        magna aliqua adipisicing elit seddo eiusmod tempor.</p>
                                    <a class="serif italic" href="#" title="Continue">Continue &raquo;</a>
                                </div>
                            </div>
                            <!-- .clearfix -->
                        </div>
                        <!-- .info-box -->
                        <div class="info-box">
                            <h3 class="info-head">Ample Customizations</h3>
                            <div class="row clearfix">
                                <div class="pull-left icons hidden-phone">
                                    <i class="icon-cogs"></i>
                                </div>
                                <div class="span3">
                                    <p>Lorem ipsum dolor sit amet consectetur incididunt ut labore et dolore
                                        magna aliqua adipisicing elit seddo eiusmod tempor.</p>
                                    <a class="serif italic" href="#" title="Continue">Continue &raquo;</a>
                                </div>
                            </div>
                            <!-- .clearfix -->
                        </div>
                        <!-- .info-box -->
                    </div>
                    <!-- .span4 -->
                    <div class="span4">
                        <div class="info-box">
                            <h3 class="info-head">Fully Responsive</h3>
                            <div class="row clearfix">
                                <div class="pull-left icons hidden-phone">
                                    <i class="icon-move"></i>
                                </div>
                                <div class="span3">
                                    <p>Lorem ipsum dolor sit amet consectetur incididunt ut labore et dolore
                                        magna aliqua adipisicing elit seddo eiusmod tempor.</p>
                                    <a class="serif italic" href="#" title="Continue">Continue &raquo;</a>
                                </div>
                            </div>
                            <!-- .clearfix -->
                        </div>
                        <!-- .info-box -->
                        <div class="info-box">
                            <h3 class="info-head">Bootstrap Compatible</h3>
                            <div class="row clearfix">
                                <div class="pull-left icons hidden-phone">
                                    <i class="icon-thumbs-up"></i>
                                </div>
                                <div class="span3">
                                    <p>Lorem ipsum dolor sit amet consectetur incididunt ut labore et dolore
                                        magna aliqua adipisicing elit seddo eiusmod tempor.</p>
                                    <a class="serif italic" href="#" title="Continue">Continue &raquo;</a>
                                </div>
                            </div>
                            <!-- .clearfix -->
                        </div>
                        <!-- .info-box -->
                    </div>
                    <!-- .span4 -->
                </div>
            </div>
        </div>
<%= render 'layouts/footer' %>

app/views/home/contact_us.html.erb
<%= render 'layouts/header' %>
        <div class="container page-content">
            <div class="row">
                <div class="span8">
                    <div class="box-container">
                        <div class="padding30">
                            <h2 class="page-title">Contact us</h2>
                            <ul class="unstyled">
                                <li>
                                    <i class="icon-envelope-alt"></i>
                                    Email: realto@realto.com</li>
                                <li>
                                    <i class="icon-phone"></i>
                                    Phone: +1 786 345 6789</li>
                                <li>
                                    <i class="icon-linkedin"></i>
                                    linkedin.com/realto</li>
                                <li>
                                    <i class="icon-twitter"></i>
                                    twitter.com/realto</li>
                            </ul>
                            <div class="row-fluid">
                                <form action="#" class="margin300" method="post" />
                                    <input class="span6" placeholder="Please, insert your name" type="text" />
                                    <input class="span6 pull-right" placeholder="Please, insert your email" type="text" />
                                    <textarea class="span12" placeholder="Write your message" rows="6"></textarea>
                                    <div class="clearfix">
                                        <button class="btn btn-realto span6" type="submit">Submit</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- .span8 -->
                <div class="span4 widget">
                    <div class="widget map box-container padding30">
                        <h3 class="widget-title">Get Directions</h3>
                        <iframe src="http://maps.google.it/maps?f=q&amp;source=s_q&amp;hl=it&amp;geocode=&amp;q=miami+beach+collins+ave+1220&amp;aq=&amp;sll=25.861386,-80.120888&amp;sspn=0.205136,0.347786&amp;ie=UTF8&amp;hq=&amp;hnear=1220+Collins+Ave,+Miami+Beach,+Miami-Dade,+Florida+33139,+Stati+Uniti&amp;t=m&amp;z=14&amp;ll=25.783255,-80.131265&amp;output=embed"></iframe>
                        <dl class="margin0">
                            <dt>Realto</dt>
                            <dd class="margin0">1680 Washington Avenue</dd>
                            <dd class="margin0">Miami Beach, FL 33139</dd>
                        </dl>
                    </div>
                </div>
                <!-- .span4 -->
            </div>
            <!-- .row -->
        </div>
        <!-- .container -->
<%= render 'layouts/footer' %>

app/views/layouts/_footer.html.erb
<footer>
<div class="container">
  <div class="row">
    <div class="span3">
      <div class="footer-widget">
      <h2 class="brand widget-title">Realto</h2>
      <p class="footer-tag-line">Your Company Tag Line</p>
      <p>Lorem ipsum dolor sit amet consectetur incididunt ut labore et dolore
                magna aliqua adipisicing elit seddo eiusmod tempor.</p>
      </div>
            <!-- .footer-company-info -->
    </div>
          <!-- .span3 -->
   <div class="span3">
    <div class="footer-widget">
    <h3 class="widget-title">Address</h3>
    <div class="clearfix">
      <ul>
        <li class="clearfix">
        <i class="icon-map-marker pull-left"></i>
        <p class="pull-left">1680 Washington Avenue
        <br />Miami Beach 33139 FL</p></li>
        <li class="clearfix">
        <i class="icon-phone pull-left"></i>
        <p class="pull-left">+1 (800) 765 4321</p></li>
        <li class="clearfix">
        <i class="icon-envelope-alt pull-left"></i>
        <p class="pull-left"><a href="#">realto@realto.com</a></p>
        </li>
      </ul>
    </div>
              <!-- .clearfix -->
    </div>
            <!-- .footer-widget -->
   </div>
          <!-- .span3 -->
<div class="span3">
   <div class="footer-widget">
    <h3 class="widget-title">Company</h3>
    <ul>
                <li>
                  <i class="icon-caret-right"></i>
                  <a title="Home" href="#">Home</a></li>
                <li>
                  <i class="icon-caret-right"></i>
                  <a title="About Us" href="#">About Us</a></li>
                <li>
                  <i class="icon-caret-right"></i>
                  <a title="Properties" href="#">Properties</a></li>
                <li>
                  <i class="icon-caret-right"></i>
                  <a title="Agents" href="#">Agents</a></li>
                <li>
                  <i class="icon-caret-right"></i>
                  <a title="Blog" href="#">Blog</a></li>
                <li>
                  <i class="icon-caret-right"></i>
                  <a title="Financing" href="#">Financing</a></li>
                <li>
                  <i class="icon-caret-right"></i>
                  <a title="Contact Us" href="#">Contact Us</a></li>
              </ul>
            </div>
            <!-- .footer-widget -->
          </div>
          <!-- .span3 -->
          <div class="span3">
            <div class="footer-widget">
              <h3 class="widget-title">Flickr</h3>
              <div class="flickr-widget">
                <ul>
                  <li class="pull-left"><a title="image" href="#"><img alt="" class="media-object" src="images/flickr-01.jpg" /></a></li>
                  <li class="pull-left"><a title="image" href="#"><img alt="" class="media-object" src="images/flickr-02.jpg" /></a></li>
                  <li class="pull-left"><a title="image" href="#"><img alt="" class="media-object" src="images/flickr-03.jpg" /></a></li>
                  <li class="pull-left"><a title="image" href="#"><img alt="" class="media-object" src="images/flickr-04.jpg" /></a></li>
                  <li class="pull-left"><a title="image" href="#"><img alt="" class="media-object" src="images/flickr-05.jpg" /></a></li>
                  <li class="pull-left"><a title="image" href="#"><img alt="" class="media-object" src="images/flickr-06.jpg" /></a></li>
                </ul>
              </div>
              <!-- .flickr-widget -->
            </div>
            <!-- .footer-widget -->
          </div>
          <!-- .span3 -->
        </div>
      </div>
    </footer>
     
    <!-- end footer -->

app/views/layouts/_header.html.erb
<header>
<div class="navbar navbar-inverse navbar-static-top">
  <div class="navbar-inner">
  <div class="container">
  <button class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse" type="button">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span></button>
  <div class="nav-collapse collapse">
      <ul class="nav">
        <li class="active"><%= link_to root_path do %><i class="icon-home"></i></li>
        <% end %>
        <li ><%= link_to "About Us", about_us_path %></li>
        <li ><%= link_to "Contact Us", contact_us_path %></li>

      </ul>
  </div>
  </div>
  </div>
</div>
<div id="logo-container">
  <div class="container">
   <div class="row">
   <div class="span8">
    <a class="brand"><span class="logo-text">SCHOOL MGMT</span></a>
    <span class="tag-line hidden-phone">Place</span>
    </div>
    <div class="span4">
    <div class="pull-right">
    <%= link_to "Sign Up", new_user_registration_path, :class =>"btn btn-primary" %>&nbsp;&nbsp;
    <%= link_to "Sign In", new_user_session_path, :class =>"btn btn-primary" %>
    </div>
    </div>
    </div>
  </div>
</div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>